create item mongoose schema and model
202309-EKTA-JO-FSW/capstone-room-5 pull request #18
Opened 2024-02-25 18:22 UTC by danasidd

closes #7

2024-02-25 18:39 UTC, belalninja commented on server/server/Models/item.js
> +    price: {
price minimum value should be 0, because a negative price is not real

2024-02-25 18:40 UTC, belalninja commented on server/server/Models/item.js
> +    itemPicture: {
itemPicture is fine if it's not required, because we can put a placeholder image in frontend if image field is absent

2024-02-25 18:45 UTC, belalninja commented on server/server/Models/item.js
we should add a required `availableQuantity` Number field with a minimum value of 0
this is my fault; I didn't write it inside ERD diagram

2024-02-25 18:45 UTC, belalninja requested changes
can you check the requested changes?
good job 👍

2024-02-26 17:46 UTC, JanaAbuHaltam approved these changes

2024-02-26 17:49 UTC, merged